spring.application.name=empresa-fornecedor

# Connection URL (format: jdbc:postgresql://<host>:<port>/<db_name>)
spring.datasource.url=jdbc:postgresql://localhost:5432/empresa-fornecedor

# Database credentials
spring.datasource.username=postgres
spring.datasource.password=marioluigi

# Driver class (optional in newer Spring Boot versions, as it is often auto-detected)
spring.datasource.driver-class-name=org.postgresql.Driver
